on: [push]

name: mabl

jobs:
  wait-for-vercel-deployment:
    runs-on: ubuntu-18.04
    steps:
      - uses: UnlyEd/github-action-await-vercel@v1.1.0
        id: await-vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
#        with:
#          deployment-url: mussia5-next.vercel.app # TODO Replace by the domain you want to test
#          timeout: 10 # Wait for 10 seconds before failing

      - name: Display deployment status
        run: "echo The deployment at ${{ fromJson(steps.await-vercel.outputs.deploymentDetails).url }} is ${{ fromJson(steps.await-vercel.outputs.deploymentDetails).readyState }}"
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: SFDigitalServices/wait-for-deployment-action@v1
        id: deployment
        with:
          token: ${{ secrets.VERCEL_TOKEN  }}
          environment: Preview
      - run: echo "${{ steps.deployment.outputs.url }}"
  test:
    needs: [wait-for-vercel-deployment]
    name: mabl Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Functional test deployment
        id: mabl-test-deployment
        uses: mablhq/github-run-tests-action@v1
        env:
          MABL_API_KEY: ${{ secrets.MABL_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          application-id: zCkW6Mhrybz0kvGKVt0VLA-a
          environment-id: HOg8AuD5iItWh6uOFnzQXg-e
#      - name: Get branch name (merge)
#        if: github.event_name != 'pull_request'
#        shell: bash
#        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
#
#      - name: Get branch name (pull request)
#        if: github.event_name == 'pull_request'
#        shell: bash
#        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV
#
#      - name: Debug
#        run: echo ${{ env.BRANCH_NAME }}
#      - name: Functional test deployment
#        id: mabl-test-deployment
#      - uses: nelonoel/branch-name@v1
#      - run: echo aris ${BRANCH_NAME}
#        uses: mablhq/github-run-tests-action@v1
#        env:
##          MABL_API_KEY: ${{ secrets.MABL_API_KEY }}
#          MABL_API_KEY: ${{ secrets.MABL_API_KEY }}
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          application-id: zCkW6Mhrybz0kvGKVt0VLA-a
#          environment-id: HOg8AuD5iItWh6uOFnzQXg-e
#          uri:
