# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test and codecov

on:
  push
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
#

jobs:
  build:

    runs-on: ubuntu-latest

#    strategy:
#      matrix:
#        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run lint
      - run: npm run test -- --coverage
#        - --coverageReporters=cobertura
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ./covarage/clover.xml
#          flags: unittests # optional
#          name: codecov-umbrella # optional
#          fail_ci_if_error: true # optional (default = false)
#          verbose: true # optional (default = false)'
      - uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          path: "./coverage/lcov.info"
          min_coverage: 80
          exclude: "**/*_observer.dart **/change.dart"
      - run: npm run build

#steps:
#  - uses: actions/checkout@master
#  - uses: codecov/codecov-action@v1
#    with:
#      token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
#      files: ./coverage1.xml,./coverage2.xml # optional
#      flags: unittests # optional
#      name: codecov-umbrella # optional
#      fail_ci_if_error: true # optional (default = false)
#      verbose: true # optional (default = false)
